<?php

namespace AppBundle\Repository;

/**
 * AlternateTitleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlternateTitleRepository extends \Doctrine\ORM\EntityRepository
{
}
