<?php

namespace AppBundle\Repository;

/**
 * ContentRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
