<?php

namespace AppBundle\Repository;

/**
 * contentRatingOrganizationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contentRatingOrganizationRepository extends \Doctrine\ORM\EntityRepository
{
}
