<?php

namespace AppBundle\Repository;

/**
 * GameRootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRootRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Used by Elastica to transform results to model
     * 
     * @param string $entityAlias
     * @return  Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias) {
//        $entityAlias = "GameRoot";
        $entityAlias2 = "game";
        $qb = $this->createQueryBuilder($entityAlias)
                ->addSelect('game')
                ->join($entityAlias . '.games', 'game')
                ->addSelect('pla')
                ->join($entityAlias2 . '.platform', 'pla')
                ->addSelect('dev')
                ->leftJoin($entityAlias2 . '.developers', 'dev')
                ->addSelect('pub')
                ->leftJoin($entityAlias2 . '.publishers', 'pub')
                ->addSelect('art')
                ->leftJoin($entityAlias2 . '.arts', 'art')
                ->addSelect('gen')
                ->leftJoin($entityAlias2 . '.genres', 'gen')
                ->addSelect('alt')
                ->leftJoin($entityAlias2 . '.alternateTitles', 'alt')
                ->addSelect('rat')
                ->leftJoin($entityAlias2 . '.contentRatings', 'rat')
        ;


        return $qb;
    }

    public function getList() {
        $entityAlias = "GameRoot";
        $entityAlias2 = "game";
        $qb = $this->createQueryBuilder($entityAlias)
                ->addSelect('game')
                ->join($entityAlias . '.games', 'game')
                ->addSelect('pla')
                ->join($entityAlias2 . '.platform', 'pla')
                ->addSelect('dev')
                ->leftJoin($entityAlias2 . '.developers', 'dev')
                ->addSelect('pub')
                ->leftJoin($entityAlias2 . '.publishers', 'pub')
                ->addSelect('art')
                ->leftJoin($entityAlias2 . '.arts', 'art')
                ->addSelect('gen')
                ->leftJoin($entityAlias2 . '.genres', 'gen')
                ->addSelect('alt')
                ->leftJoin($entityAlias2 . '.alternateTitles', 'alt')
                ->addSelect('rat')
                ->leftJoin($entityAlias2 . '.contentRatings', 'rat')
        ;


        return $qb;
    }

}
