<?php

namespace AppBundle\Repository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * Used by Elastica to transform results to model
     * 
     * @param string $entityAlias
     * @return  Doctrine\ORM\QueryBuilder
     */
    public function createSearchQueryBuilder($entityAlias) {

        $qb = $this->createQueryBuilder($entityAlias)
                ->addSelect('pla')
                ->join($entityAlias . '.platform', 'pla')
                ->addSelect('dev')
                ->leftJoin($entityAlias . '.developers', 'dev')
                ->addSelect('pub')
                ->leftJoin($entityAlias . '.publishers', 'pub');


        return $qb;
    }

}
