<?php

namespace AppBundle\Repository;

/**
 * GameLinkTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameLinkTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
