<?php

namespace AppBundle\Repository;

/**
 * GameRootRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRootRepository extends \Doctrine\ORM\EntityRepository
{
}
