<?php

namespace AppBundle\Repository;

/**
 * GameLinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameLinkRepository extends \Doctrine\ORM\EntityRepository
{
}
