<?php

namespace AppBundle\Repository;

/**
 * GameVersionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameVersionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
