<?php

namespace AppBundle\Repository;

/**
 * GenerationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationRepository extends \Doctrine\ORM\EntityRepository
{
}
