<?php

namespace AppBundle\Repository;

/**
 * PlatformTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
