<?php

namespace AppBundle\Repository;

/**
 * PlatformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatformRepository extends \Doctrine\ORM\EntityRepository {

    public function getPlatformComplete($idPlatform) {
        $entityAlias = "Platform";
        $qb = $this->createQueryBuilder($entityAlias)
                ->addSelect('dev')
                ->leftJoin($entityAlias . '.developers', 'dev')
                ->addSelect('man')
                ->leftJoin($entityAlias . '.manufacturers', 'man')
                ->addSelect('art')
                ->leftJoin($entityAlias . '.arts', 'art')
                ->andWhere($entityAlias . '.id = ?1')
                ->setParameter(1, $idPlatform)
        ;


        return $qb;
    }

    public function getAllComplete() {
        $entityAlias = "Platform";
        $qb = $this->createQueryBuilder($entityAlias)
                ->addSelect('dev')
                ->leftJoin($entityAlias . '.developers', 'dev')
                ->addSelect('man')
                ->leftJoin($entityAlias . '.manufacturers', 'man')
                ->addSelect('art')
                ->leftJoin($entityAlias . '.arts', 'art')
        ;


        return $qb;
    }

    public function getAllBase() {
        $entityAlias = "Platform";
        $qb = $this->createQueryBuilder($entityAlias)
        ;

        return $qb;
    }

}
