<?php

namespace AppBundle\Repository;

/**
 * RegionCountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RegionCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
