## YAML Template.
---
fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        opengamedb:
            client: default
            finder : ~
            types:
                game:
                    mappings:
                        title : ~
                        alternateTitles:
                            type: "nested"
                            properties:
                                title: ~
                                id: ~
                    persistence:
                        driver: orm
                        model: AppBundle\Entity\Game
                        elastica_to_model_transformer:
                            query_builder_method: createSearchQueryBuilder
                        finder: ~
                        provider: ~
                        listener: ~