app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group 
    
#API
games:
    type:     rest
    resource: "@AppBundle/API/"
    prefix: /api
    
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /apidocumentation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"
    
oneup_uploader:
    resource: .
    type: uploader
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
    
#SONATA
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
#phpcr_admin:
#    resource: '@SonataDoctrinePhpcrAdminBundle/Resources/config/routing/tree.xml'
#    prefix: /admin

sonata_phpcr_admin_tree:
    resource: '@SonataDoctrinePHPCRAdminBundle/Resources/config/routing/tree.xml'
    prefix: /admin
    
#cmf_tree:
#    resource: .
#    type: 'cmf_tree'

cmf_resource:
    resource: '@CmfResourceRestBundle/Resources/config/routing.yml'
    prefix: /admin