# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    
    AppBundle.importcsv:
        class: AppBundle\Manager\ImportCSV
        arguments: ["@service_container"]
        
    app_bundle.service.listener:
        class: AppBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
        arguments: [ "@service_container" ]