# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    
#    Managers
    AppBundle.importcsv:
        class: AppBundle\Manager\ImportCSV
        arguments: ["@service_container"]
        
    AppBundle.vanillajsconnect:
        class: AppBundle\Manager\VanillaJsConnect
        arguments: ["@service_container"]
        
#   Full calendar
    app_bundle.service.listener:
        class: AppBundle\Listener\LoadDataListener
        tags:
            - { name: 'kernel.event_listener', event: 'fullcalendar.set_data', method: loadData }
        arguments: [ "@service_container" ]
        
    #twig extensions
    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
            - { name: twig.extension }
 
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }    
            
    appBundle.upload_listener:
        class: AppBundle\Listener\UploadListener
        arguments: ["@doctrine.orm.entity_manager", "@service_container"]
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }